"""
brillouin.py — Spontaneous Brillouin Scattering (SpBS) noise for BIFROST.

Models the photon noise generated by stimulated/spontaneous Brillouin
scattering (SBS/SpBS) when a classical pump channel propagates in an optical
fiber co-located with a quantum channel.

Overview of Brillouin scattering in fibers
------------------------------------------
Brillouin scattering arises from the interaction of light with *acoustic*
(longitudinal, thermally-driven) phonons in the glass matrix, in contrast to
Raman scattering which couples to optical phonons.  The key differences are:

  Property              Brillouin          Raman
  ──────────────────────────────────────────────────────────────────
  Phonon frequency      ~11 GHz            ~13 THz
  n_th at 300 K         ~560               ~0.14    (n_th >> 1: classical)
  g_peak                ~5e-11 m/W         ~7e-4 m/W    (10^7x larger!)
  Spectral bandwidth    ~25 MHz            ~25 THz
  Direction             BACKWARD           Forward (in standard fiber SBS)
  SBS threshold (25km)  ~3.7 mW            ~12 mW  (Raman 10% depletion)

Backward-only geometry
-----------------------
In single-mode fiber the dominant Brillouin process is **backward stimulated
Brillouin scattering (BSBS)**: a pump photon at omega_p creates a backward-
propagating Stokes photon at omega_s = omega_p - Omega_B.  Phase matching in
the backward direction forces:

    k_p + k_s = q_acoustic   =>   nu_B = 2 * n_eff * v_A / lambda_pump

Forward Brillouin (GAWBS) exists but is ~30 dB weaker and concentrated at
sub-MHz acoustic resonances; it is not modelled here.

Consequences for WDM quantum networks
--------------------------------------
1. **SBS threshold (~3.7 mW at 25 km SMF-28)** limits usable pump power.
   Above P_th, the pump is exponentially depleted and a large backward
   Stokes field builds up.  This is 3x below the Raman depletion threshold.

2. **Backward SpBS noise** exits at z=0 propagating backward.  It does not
   directly enter a co-propagating quantum channel, but it does:
   (a) enter a counter-propagating quantum channel near nu_pump - nu_B;
   (b) set the maximum power budget for all noise processes.

3. **Spectral isolation**: nu_B ~ 11 GHz corresponds to only ~0.09 nm at
   1550 nm.  WDM quantum channels separated by > 0.1 nm from the pump are
   unaffected by Brillouin noise directly.

Sign / frequency convention (consistent with raman.py)
-------------------------------------------------------
  Omega > 0:  Stokes sideband,  omega_Stokes = omega_pump - Omega  (backward)
  Omega_B = 2*pi * nu_B  (Brillouin shift, positive, ~69 Grad/s)

Key references
--------------
[B1] Agrawal, G.P., Nonlinear Fiber Optics, 6th ed. (Academic, 2019), §9.1-9.2.
[B2] Smith, R.G., Appl. Opt. 11, 2489 (1972).  [SBS threshold formula, G_B=21]
[B3] Nikles, M. et al., J. Lightwave Technol. 15, 1842 (1997).
     [Measured g_B and linewidth vs doping; temperature dependence]
[B4] Kobyakov, A., Sauer, M., Chowdhury, D., Adv. Opt. Photon. 2, 1 (2010).
     [Comprehensive SBS review in optical fibers]
[B5] Tkach, R.W. et al., J. Lightwave Technol. 5, 1380 (1987).
     [Brillouin shift vs GeO2 concentration]
[B6] Peters, N.A. et al., New J. Phys. 11, 045012 (2009).  [WDM quantum context]
[B7] Boyd, R.W., Nonlinear Optics, 4th ed. (Academic, 2020), §9.3.

Patrick Banner / Britton Lab extension
Dept. of Physics, Swarthmore College / JQI, UMD
"""

import warnings
import numpy as np
from scipy.integrate import simpson

# ─────────────────────────────────────────────────────────────────────────────
# Physical constants  (match raman.py exactly)
# ─────────────────────────────────────────────────────────────────────────────

_hbar = 1.054571817e-34    # Reduced Planck constant (J*s)
_kB   = 1.380649e-23       # Boltzmann constant (J/K)
_c    = 299792458.0        # Speed of light in vacuum (m/s)
_pi   = np.pi

# ─────────────────────────────────────────────────────────────────────────────
# Brillouin material parameters
# ─────────────────────────────────────────────────────────────────────────────

BRIL_VA_SIO2  = 5970.0    # m/s  longitudinal acoustic velocity, pure SiO2
                           # Agrawal Table 9.1; Nikles (1997)
BRIL_VA_COEFF = -0.274    # fractional change per unit GeO2 mole fraction
                           # v_A(x) = v_A_SiO2 * (1 + BRIL_VA_COEFF * x)
                           # Tkach et al. (1987); Nikles (1997)

BRIL_G_PEAK   = 5.0e-11   # m/W  peak Brillouin gain coefficient, pure SiO2
                           # Agrawal Table 9.1; Kobyakov (2010) review
                           # Literature range: 2-5 x 10^{-11} m/W

BRIL_DFREQ_HZ = 25.0e6    # Hz   FWHM Lorentzian linewidth, SMF-28, 300 K
                           # Nikles (1997): 20-50 MHz; Kobyakov: ~27 MHz
BRIL_GAMMA_RAD = 2*_pi * BRIL_DFREQ_HZ   # rad/s FWHM

BRIL_G_THRESH = 21.0      # dimensionless SBS threshold gain factor
                           # Smith (1972): G_B = 21 for thermally-seeded
                           # passive fiber.  Some authors use 20 or 25.

# ─────────────────────────────────────────────────────────────────────────────
# Fiber loss model  (copy of raman.py to avoid circular import)
# ─────────────────────────────────────────────────────────────────────────────

_LOSS_A_RAY  = 0.78     # dB/km * um^4  (Rayleigh scattering)
_LOSS_FLOOR  = 0.065    # dB/km         (IR absorption floor)


def _fiber_loss_m(wavelength_m):
    """Power loss coefficient alpha (m^-1), SMF-28 empirical model."""
    wavelength_m = np.asarray(wavelength_m, dtype=float)
    lam_um = wavelength_m * 1e6
    dB_km  = _LOSS_A_RAY / lam_um**4 + _LOSS_FLOOR
    return dB_km / (10.0 * np.log10(np.e)) / 1e3


# ─────────────────────────────────────────────────────────────────────────────
# Core Brillouin functions
# ─────────────────────────────────────────────────────────────────────────────

def brillouin_freq_shift(lambda_pump,
                          n_eff=1.4447,
                          v_acoustic=BRIL_VA_SIO2,
                          m_GeO2=0.0):
    """
    Brillouin frequency shift nu_B for backward SBS in optical fiber.

    Phase-matching for backward scattering (k_p + k_s = q_acoustic):

        nu_B = 2 * n_eff * v_A / lambda_pump

    Parameters
    ----------
    lambda_pump : float or array_like
        Pump wavelength in vacuum (m).
    n_eff : float, optional
        Phase refractive index of LP01 mode at lambda_pump.
        Default: 1.4447 (SMF-28 at 1550 nm).
    v_acoustic : float, optional
        Longitudinal acoustic velocity (m/s).  Default: 5970 m/s (pure SiO2).
    m_GeO2 : float, optional
        GeO2 mole fraction (0 = pure SiO2).  Corrects acoustic velocity via
        v_A(x) = v_acoustic * (1 + BRIL_VA_COEFF * x).  Default: 0.

    Returns
    -------
    float or np.ndarray
        Brillouin frequency shift nu_B (Hz).

    Notes
    -----
    nu_B scales as 1/lambda, so:
        1310 nm: nu_B ~ 13.2 GHz
        1550 nm: nu_B ~ 11.1 GHz
        1620 nm: nu_B ~ 10.6 GHz

    The LP01 mode propagates mostly in the SiO2 cladding for SMF-28
    (V ~ 2.0), so the pure-SiO2 acoustic velocity is a good approximation.
    For strongly-doped specialty fibers, supply the actual m_GeO2.

    Examples
    --------
    >>> brillouin_freq_shift(1550e-9)
    11128677143.0   # Hz = 11.13 GHz
    """
    v_A = v_acoustic * (1.0 + BRIL_VA_COEFF * m_GeO2)
    return 2.0 * n_eff * v_A / np.asarray(lambda_pump, dtype=float)


def g_B_lorentzian(Omega, Omega_B, g_B_peak=BRIL_G_PEAK, Gamma_B=BRIL_GAMMA_RAD):
    """
    Brillouin gain spectrum: normalised Lorentzian lineshape.

        g_B(Omega) = g_B_peak * (Gamma_B/2)^2 / [(Omega - Omega_B)^2 + (Gamma_B/2)^2]

    The Lorentzian arises from the damped acoustic-phonon propagator
    (electrostriction coupling; see Agrawal [B1] §2.3, §9.1).

    Parameters
    ----------
    Omega : array_like
        Angular frequency offset from pump (rad/s).  Peaks at Omega = Omega_B.
    Omega_B : float
        Brillouin angular shift (rad/s) = 2*pi * nu_B.
    g_B_peak : float, optional
        Peak gain at Omega = Omega_B (m/W).  Default: BRIL_G_PEAK = 5e-11.
    Gamma_B : float, optional
        FWHM linewidth (rad/s).  Default: BRIL_GAMMA_RAD = 2*pi*25 MHz.

    Returns
    -------
    np.ndarray
        g_B(Omega) (m/W).

    Notes
    -----
    Analytical integral: integral g_B dOmega = g_B_peak * pi * Gamma_B / 2.
    HWHM: g_B(Omega_B +/- Gamma_B/2) = g_B_peak / 2.

    Examples
    --------
    >>> nu_B  = brillouin_freq_shift(1550e-9)
    >>> Om_B  = 2 * np.pi * nu_B
    >>> g_B_lorentzian(Om_B, Om_B)    # 5e-11 (peak)
    >>> g_B_lorentzian(Om_B + BRIL_GAMMA_RAD/2, Om_B)  # 2.5e-11 (HWHM)
    """
    Omega = np.asarray(Omega, dtype=float)
    hwhm  = Gamma_B / 2.0
    return g_B_peak * hwhm**2 / ((Omega - Omega_B)**2 + hwhm**2)


def effective_length_backward(L, alpha_pump, alpha_signal=None):
    """
    Effective interaction length for backward-propagating Stokes noise.

    For backward Brillouin (pump +z, Stokes -z), a Stokes photon born at
    position z experiences:
        pump power:         P_p * exp(-alpha_p * z)
        Stokes survival:    exp(-alpha_s * z)   (travels back to z=0)

    Integrating over z in [0, L]:

        L_eff_back = integral_0^L exp(-(alpha_p + alpha_s) * z) dz
                   = [1 - exp(-(alpha_p + alpha_s) * L)] / (alpha_p + alpha_s)

    Compare to forward Raman effective length (in raman.py):
        L_eff_fwd = [exp(-alpha_p*L) - exp(-alpha_s*L)] / (alpha_s - alpha_p)

    The backward formula gives approximately L/2 the forward value for
    equal losses, since the Stokes accumulates loss over the full fiber
    distance twice (once for pump attenuation, once for Stokes propagation
    back to the input).

    Parameters
    ----------
    L : float
        Physical fiber length (m).
    alpha_pump : float or array_like
        Pump power attenuation coefficient (m^-1).
    alpha_signal : float or array_like, optional
        Stokes loss coefficient (m^-1).  Default: alpha_pump (Brillouin
        shift of 11 GHz is negligible compared to fiber loss variations).

    Returns
    -------
    np.ndarray
        L_eff_back (m).  Long-fiber limit: 1/(alpha_p + alpha_s) ~ 10.9 km.

    Notes
    -----
    Forward (Raman) L_eff: asymptote 1/alpha ~ 21.7 km  (0.2 dB/km, 1550 nm)
    Backward (Brillouin) L_eff: asymptote 1/(2*alpha) ~ 10.9 km
    Ratio: L_eff_back / L_eff_fwd -> 0.5 as L -> infinity.
    """
    alpha_pump = np.asarray(alpha_pump, dtype=float)
    if alpha_signal is None:
        alpha_signal = alpha_pump
    else:
        alpha_signal = np.asarray(alpha_signal, dtype=float)

    alpha_sum = alpha_pump + alpha_signal
    # Numerically stable: (1 - exp(-x))/x = -expm1(-x)/x; limit x->0 is L
    safe = np.where(alpha_sum > 1e-12, alpha_sum, 1.0)
    Leff = -np.expm1(-safe * L) / safe
    return np.where(alpha_sum > 1e-12, Leff, float(L))


def thermal_phonon_number(Omega, T_K):
    """
    Bose-Einstein phonon occupancy: n_th(Omega, T) = 1 / (exp(hbar*Omega/kB*T) - 1).

    At Brillouin frequencies (~11 GHz) and room temperature (300 K):
        x = hbar * Omega_B / (kB * T) ~ 1.78e-3  (x << 1, classical limit)
        n_th ~ kB*T / (hbar * Omega_B) ~ 561

    This enormous thermal occupancy (n_th >> 1) is the reason spontaneous
    Brillouin noise is so much larger per unit bandwidth than Raman noise,
    despite the smaller total bandwidth.

    Parameters
    ----------
    Omega : array_like
        Phonon angular frequency (rad/s).
    T_K : float
        Temperature (K).

    Returns
    -------
    np.ndarray
        n_th, same shape as Omega.
    """
    Omega = np.asarray(np.abs(Omega), dtype=float)
    x = _hbar * Omega / (_kB * T_K)
    return np.where(x > 500.0, 0.0, 1.0 / np.expm1(x))


# ─────────────────────────────────────────────────────────────────────────────
# SBS threshold
# ─────────────────────────────────────────────────────────────────────────────

def brillouin_threshold(A_eff, L, alpha=None, lambda_pump=1550e-9,
                         g_B_peak=BRIL_G_PEAK, G_th=BRIL_G_THRESH):
    """
    SBS threshold pump power using the Smith (1972) criterion [B2].

        P_th = G_th * A_eff / (g_B * L_eff_back)

    where L_eff_back = [1 - exp(-2*alpha*L)] / (2*alpha) and G_th = 21.

    Parameters
    ----------
    A_eff : float
        Effective mode area (m^2).
    L : float
        Fiber length (m).
    alpha : float, optional
        Power attenuation coefficient (m^-1).  None uses SMF-28 model.
    lambda_pump : float, optional
        Pump wavelength (m).  Default: 1550 nm.
    g_B_peak : float, optional
        Peak Brillouin gain (m/W).  Default: BRIL_G_PEAK.
    G_th : float, optional
        Threshold gain factor.  Default: 21 (Smith 1972).
        Some sources use 20 (exact) or 25 (practical conservative).

    Returns
    -------
    dict
        P_threshold_W    : float  -- SBS threshold (W)
        P_threshold_mW   : float  -- SBS threshold (mW)
        G_B_at_threshold : float  -- gain factor used
        L_eff_back_m     : float  -- backward effective length (m)
        g_B_peak         : float  -- peak gain used (m/W)
        alpha_m          : float  -- loss coefficient (m^-1)
        formula          : str    -- human-readable summary

    Notes
    -----
    The threshold is a soft limit.  Above P_th, SBS converts pump photons
    to backward Stokes photons exponentially, depleting the pump and
    reducing the SNR of PMD measurements.  For SMF-28 at 1550 nm and 25 km:
    P_th ~ 3.6 mW -- readily exceeded in DWDM systems.

    Examples
    --------
    >>> result = brillouin_threshold(A_eff=85e-12, L=25e3)
    >>> print(f"P_th = {result['P_threshold_mW']:.2f} mW")
    P_th = 3.65 mW
    """
    if alpha is None:
        alpha = float(_fiber_loss_m(lambda_pump))

    Leff_back = float(effective_length_backward(L, alpha, alpha))
    P_th = G_th * A_eff / (g_B_peak * Leff_back)

    return {
        'P_threshold_W':     P_th,
        'P_threshold_mW':    P_th * 1e3,
        'G_B_at_threshold':  G_th,
        'L_eff_back_m':      Leff_back,
        'g_B_peak':          g_B_peak,
        'alpha_m':           alpha,
        'formula': (
            f"P_th = {G_th} x A_eff / (g_B x L_eff_back)"
            f" = {G_th} x {A_eff*1e12:.1f}um^2 / "
            f"({g_B_peak:.1e} m/W x {Leff_back/1e3:.2f} km)"
            f" = {P_th*1e3:.2f} mW"
        ),
    }


def check_sbs_threshold(P_pump, A_eff, L, alpha=None, lambda_pump=1550e-9,
                         g_B_peak=BRIL_G_PEAK, threshold_fraction=0.80):
    """
    Check if pump power is near or above the SBS threshold.

    Issues a UserWarning if P_pump > threshold_fraction * P_th.

    Parameters
    ----------
    P_pump : float
        Pump power at fiber input (W).
    A_eff : float
        Effective mode area (m^2).
    L : float
        Fiber length (m).
    alpha : float, optional
        Loss coefficient (m^-1).  None uses SMF-28 model.
    lambda_pump : float, optional
        Pump wavelength (m).  Default: 1550 nm.
    g_B_peak : float, optional
        Peak Brillouin gain (m/W).
    threshold_fraction : float, optional
        Warn if P_pump exceeds this fraction of P_th.  Default: 0.80.

    Returns
    -------
    dict
        P_threshold_W           : float
        P_pump_W                : float
        fraction_of_threshold   : float  -- P_pump / P_th
        sbs_gain_parameter      : float  -- G_B = g_B * P * L_eff / A_eff
        above_threshold         : bool
        valid                   : bool   -- True if below warning level
        recommendation          : str

    Examples
    --------
    >>> check_sbs_threshold(P_pump=5e-3, A_eff=85e-12, L=25e3)
    UserWarning: Pump power (5.00 mW) is 137% of SBS threshold (3.65 mW) ...
    """
    thresh = brillouin_threshold(A_eff, L, alpha, lambda_pump, g_B_peak)
    P_th   = thresh['P_threshold_W']
    G_B    = g_B_peak * P_pump * thresh['L_eff_back_m'] / A_eff
    frac   = P_pump / P_th
    above  = frac > 1.0
    valid  = frac < threshold_fraction

    if not valid:
        warnings.warn(
            f"Pump power ({P_pump*1e3:.2f} mW) is {frac*100:.0f}% of the "
            f"SBS threshold ({P_th*1e3:.2f} mW, L={L/1e3:.0f} km, "
            f"g_B={g_B_peak:.1e} m/W).  "
            f"Consider SBS suppression (phase dithering) or reducing pump power.",
            UserWarning, stacklevel=2)

    rec = (
        f"P_pump = {P_pump*1e3:.2f} mW is "
        + ("ABOVE" if above else f"{frac*100:.0f}% of")
        + f" SBS threshold ({P_th*1e3:.2f} mW).  "
        + ("Pump WILL be depleted." if above
           else "Safe." if valid
           else "Approaching threshold -- monitor pump depletion.")
    )

    return {
        'P_threshold_W':         P_th,
        'P_pump_W':              P_pump,
        'fraction_of_threshold': frac,
        'sbs_gain_parameter':    G_B,
        'above_threshold':       above,
        'valid':                 valid,
        'recommendation':        rec,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Spontaneous Brillouin photon rate spectral density
# ─────────────────────────────────────────────────────────────────────────────

def spBril_photon_rate_density(Omega, lambda_pump, P_pump, L, A_eff, T_K,
                                n_eff=1.4447,
                                v_acoustic=BRIL_VA_SIO2,
                                m_GeO2=0.0,
                                g_B_peak=BRIL_G_PEAK,
                                Gamma_B=BRIL_GAMMA_RAD,
                                alpha_pump=None,
                                alpha_signal=None):
    """
    Spectral density of spontaneous Brillouin scattered photons (backward Stokes).

    Returns dN_dot/dOmega [photons / (s * rad/s)] at the fiber input end (z=0)
    for the backward-propagating spontaneous Stokes field.

    The formula follows the Raman analogue (raman.py) but uses:
      (1) the Lorentzian g_B(Omega) instead of the broad Raman spectrum;
      (2) the backward effective length L_eff_back;
      (3) n_th(Omega_B, T) >> 1 (classical thermal phonons at GHz freqs).

        dN_dot/dOmega = (1/2pi) * (g_B(Omega)/A_eff) * P_pump * L_eff_back * n_th

    Note: g_B is conventionally defined per unit intensity (W/m^2) times
    length (m).  The power gain coefficient is g_B/A_eff * P (m^-1).

    Parameters
    ----------
    Omega : array_like
        Angular frequency offset from pump (rad/s).
    lambda_pump : float
        Pump wavelength (m).
    P_pump : float
        Pump power at fiber input (W).
    L : float
        Fiber length (m).
    A_eff : float
        Effective mode area (m^2).
    T_K : float
        Temperature (K).
    n_eff : float, optional
        Phase refractive index.  Default: 1.4447 (SMF-28 @ 1550 nm).
    v_acoustic : float, optional
        Acoustic velocity (m/s).  Default: 5970 m/s.
    m_GeO2 : float, optional
        GeO2 mole fraction.  Default: 0.
    g_B_peak : float, optional
        Peak Brillouin gain (m/W).
    Gamma_B : float, optional
        Brillouin FWHM linewidth (rad/s).
    alpha_pump, alpha_signal : float, optional
        Loss coefficients (m^-1).  None uses SMF-28 model.
        Since the Brillouin shift is only 11 GHz, alpha_signal ~ alpha_pump.

    Returns
    -------
    np.ndarray
        dN_dot/dOmega (photons/s/(rad/s)).  Noise exits at z=0 backward.

    Notes
    -----
    Geometry: The returned noise exits at z=0 travelling backward.  For
    co-propagating WDM quantum channels this does NOT directly reach the
    quantum channel detector.  It is relevant for:
      (a) counter-propagating quantum channels near nu_pump - nu_B;
      (b) the SBS threshold, which limits pump power for all channels.

    The Brillouin line is only ~25 MHz wide.  For integrated noise, use
    spBril_noise_in_channel().
    """
    Omega = np.asarray(Omega, dtype=float)

    nu_B    = brillouin_freq_shift(lambda_pump, n_eff, v_acoustic, m_GeO2)
    Omega_B = 2.0 * _pi * nu_B

    if alpha_pump is None:
        alpha_pump = float(_fiber_loss_m(lambda_pump))
    if alpha_signal is None:
        alpha_signal = alpha_pump   # Brillouin Stokes only 11 GHz from pump

    Leff_back = effective_length_backward(L, alpha_pump, alpha_signal)
    gB        = g_B_lorentzian(Omega, Omega_B, g_B_peak, Gamma_B)
    nth       = thermal_phonon_number(Omega, T_K)

    return (1.0 / (2.0 * _pi)) * (gB / A_eff) * P_pump * Leff_back * nth


def spBril_noise_in_channel(lambda_pump, lambda_channel, delta_lambda,
                              P_pump, L, A_eff, T_K,
                              N_points=501,
                              n_eff=1.4447,
                              v_acoustic=BRIL_VA_SIO2,
                              m_GeO2=0.0,
                              g_B_peak=BRIL_G_PEAK,
                              Gamma_B=BRIL_GAMMA_RAD,
                              alpha_pump=None,
                              alpha_signal=None):
    """
    Total spontaneous Brillouin noise (backward) in a specified channel bandwidth.

    Integrates spBril_photon_rate_density() over the channel filter bandwidth.

    Parameters
    ----------
    lambda_pump : float
        Pump wavelength (m).
    lambda_channel : float
        Quantum channel center wavelength (m).
        For significant noise, |lambda_channel - lambda_pump| must be near
        delta_lambda_B = lambda^2 * nu_B / c ~ 0.09 nm at 1550 nm.
    delta_lambda : float
        Channel filter bandwidth (m, full-width).
    P_pump : float
        Pump power at fiber input (W).
    L : float
        Fiber length (m).
    A_eff : float
        Effective mode area (m^2).
    T_K : float
        Temperature (K).
    N_points : int, optional
        Integration quadrature points (odd).  Default: 501.
        Use >= 1001 when delta_lambda < 10x the Brillouin linewidth (~0.9 MHz).
    n_eff, v_acoustic, m_GeO2, g_B_peak, Gamma_B, alpha_pump, alpha_signal
        Forwarded to spBril_photon_rate_density().

    Returns
    -------
    dict
        backward_photon_rate           : float  -- photons/s at z=0 (backward)
        backward_power_W               : float  -- equivalent noise power (W)
        Omega_B_rad                    : float  -- Brillouin shift (rad/s)
        nu_B_Hz                        : float  -- Brillouin shift (Hz)
        delta_lambda_B_pm              : float  -- Brillouin wavelength shift (pm)
        lambda_Stokes_nm               : float  -- Stokes wavelength (nm)
        channel_is_near_Brillouin      : bool   -- True if channel overlaps ν_B
        P_threshold_mW                 : float  -- SBS threshold (mW)
        pump_fraction_of_threshold     : float  -- P_pump / P_th
        lambda_pump                    : float
        lambda_channel                 : float
        delta_lambda                   : float

    Notes
    -----
    For quantum channels far from nu_pump - nu_B (the standard WDM case),
    this returns essentially zero.  The Brillouin line is only 25 MHz wide.

    The SBS threshold is always reported because it constrains pump power
    across all WDM channels, regardless of spectral overlap.

    Examples
    --------
    # Channel at Brillouin Stokes wavelength:
    >>> nu_B  = brillouin_freq_shift(1550e-9)
    >>> lam_B = _c / (_c / 1550e-9 - nu_B)
    >>> result = spBril_noise_in_channel(1550e-9, lam_B, 0.1e-9,
    ...                                  P_pump=1e-3, L=25e3,
    ...                                  A_eff=85e-12, T_K=300)
    >>> print(result['backward_photon_rate'])

    # Normal WDM channel (far from Brillouin):
    >>> result2 = spBril_noise_in_channel(1310e-9, 1550e-9, 1e-9,
    ...                                   P_pump=1e-3, L=25e3,
    ...                                   A_eff=85e-12, T_K=300)
    >>> print(result2['backward_photon_rate'])   # ~ 0
    """
    if N_points % 2 == 0:
        N_points += 1

    omega_pump    = 2.0 * _pi * _c / lambda_pump
    omega_channel = 2.0 * _pi * _c / lambda_channel

    nu_B    = float(brillouin_freq_shift(lambda_pump, n_eff, v_acoustic, m_GeO2))
    Omega_B = 2.0 * _pi * nu_B
    # Stokes wavelength: lambda_s = c / (nu_pump - nu_B)
    lambda_Stokes = _c / (_c / lambda_pump - nu_B)
    delta_lambda_B_pm = abs(lambda_Stokes - lambda_pump) * 1e12

    # Is channel spectrally near the Brillouin line?
    nu_channel_offset = abs(_c / lambda_channel - (_c / lambda_pump - nu_B))
    near_brillouin    = nu_channel_offset < 10.0 * BRIL_DFREQ_HZ

    # Wavelength grid over channel filter
    lam_arr = np.linspace(lambda_channel - delta_lambda / 2.0,
                           lambda_channel + delta_lambda / 2.0,
                           N_points)
    om_arr  = 2.0 * _pi * _c / lam_arr
    Omega_arr = np.abs(omega_pump - om_arr)

    # Loss
    alpha_p = float(alpha_pump) if alpha_pump is not None else float(_fiber_loss_m(lambda_pump))
    alpha_s_arr = (_fiber_loss_m(lam_arr) if alpha_signal is None
                   else float(alpha_signal) * np.ones_like(lam_arr))

    # Backward L_eff (array over channel wavelengths)
    Leff_arr = effective_length_backward(L, alpha_p, alpha_s_arr)

    # Spectral noise density
    gB_arr  = g_B_lorentzian(Omega_arr, Omega_B, g_B_peak, Gamma_B)
    nth_arr = thermal_phonon_number(Omega_arr, T_K)
    dNdOm   = (1.0 / (2.0 * _pi)) * (gB_arr / A_eff) * P_pump * Leff_arr * nth_arr

    # Integrate: dOmega = (2*pi*c/lambda^2) dlambda
    photon_rate = float(simpson(dNdOm * (2.0 * _pi * _c / lam_arr**2), x=lam_arr))
    power_W     = photon_rate * _hbar * omega_channel

    # SBS threshold
    thresh = brillouin_threshold(A_eff, L, alpha_p, lambda_pump, g_B_peak)

    return {
        'backward_photon_rate':         photon_rate,
        'backward_power_W':             power_W,
        'Omega_B_rad':                  Omega_B,
        'nu_B_Hz':                      nu_B,
        'delta_lambda_B_pm':            delta_lambda_B_pm,
        'lambda_Stokes_nm':             lambda_Stokes * 1e9,
        'channel_is_near_Brillouin':    near_brillouin,
        'P_threshold_mW':               thresh['P_threshold_mW'],
        'pump_fraction_of_threshold':   P_pump / thresh['P_threshold_W'],
        'lambda_pump':                  lambda_pump,
        'lambda_channel':               lambda_channel,
        'delta_lambda':                 delta_lambda,
    }


def brillouin_gain_profile(lambda_pump, freq_range_GHz=(-100, 100), N=4096,
                            n_eff=1.4447, v_acoustic=BRIL_VA_SIO2, m_GeO2=0.0,
                            g_B_peak=BRIL_G_PEAK, Gamma_B=BRIL_GAMMA_RAD):
    """
    Compute the Brillouin gain profile over a frequency range around the pump.

    Useful for plotting and spectral-overlap checks.

    Parameters
    ----------
    lambda_pump : float
        Pump wavelength (m).
    freq_range_GHz : tuple (lo, hi), optional
        Frequency offset range relative to pump (GHz).  Default: (-100, 100).
    N : int, optional
        Number of frequency points.  Default: 4096.
    n_eff, v_acoustic, m_GeO2, g_B_peak, Gamma_B : optional
        Brillouin parameters.

    Returns
    -------
    dict
        freq_offset_GHz : np.ndarray  -- frequency offset from pump (GHz)
        wavelength_m    : np.ndarray  -- corresponding wavelengths (m)
        g_B_mW          : np.ndarray  -- g_B (m/W)
        nu_B_GHz        : float       -- Brillouin shift (GHz)
        g_B_peak        : float       -- peak gain (m/W)
        Gamma_B_MHz     : float       -- linewidth FWHM (MHz)
    """
    nu_B    = float(brillouin_freq_shift(lambda_pump, n_eff, v_acoustic, m_GeO2))
    Omega_B = 2.0 * _pi * nu_B
    nu_pump = _c / lambda_pump

    nu_arr  = np.linspace(nu_pump + freq_range_GHz[0]*1e9,
                           nu_pump + freq_range_GHz[1]*1e9, N)
    Om_arr  = 2.0 * _pi * np.abs(nu_arr - nu_pump)
    gB_arr  = g_B_lorentzian(Om_arr, Omega_B, g_B_peak, Gamma_B)

    return {
        'freq_offset_GHz': (nu_arr - nu_pump) / 1e9,
        'wavelength_m':    _c / nu_arr,
        'g_B_mW':          gB_arr,
        'nu_B_GHz':        nu_B / 1e9,
        'g_B_peak':        g_B_peak,
        'Gamma_B_MHz':     Gamma_B / (2.0 * _pi * 1e6),
    }


# ─────────────────────────────────────────────────────────────────────────────
# Runtime attachment to FiberLength instances
# ─────────────────────────────────────────────────────────────────────────────

def install_brillouin_methods(fiber_obj):
    """
    Attach Brillouin noise methods to an existing FiberLength instance.

    After calling this, the object gains:
        fiber.calcSpBrilNoise(lambda_ref, lambda_quantum, delta_lambda, P_ref)
        fiber.brillouinThreshold(lambda_ref=1550e-9)
        fiber.checkSBSThreshold(P_pump, lambda_ref=1550e-9)

    Parameters
    ----------
    fiber_obj : FiberLength instance
        Must have .Aeff, .Lt or .L0, and .T0 attributes.

    Returns
    -------
    fiber_obj  (same object, with new methods attached)

    Examples
    --------
    >>> import fibers, brillouin
    >>> f = fibers.FiberLength(...)
    >>> brillouin.install_brillouin_methods(f)
    >>> thresh = f.brillouinThreshold()
    >>> noise  = f.calcSpBrilNoise(1550e-9, 1550.09e-9, 0.1e-9, 1e-3)
    """
    import types

    def _calcSpBrilNoise(self, lambda_ref, lambda_quantum, delta_lambda,
                          P_ref, **kwargs):
        T_K = getattr(self, 'T0', 22.0) + 273.15
        L   = getattr(self, 'Lt', getattr(self, 'L0', None))
        return spBril_noise_in_channel(
            lambda_pump=lambda_ref, lambda_channel=lambda_quantum,
            delta_lambda=delta_lambda, P_pump=P_ref,
            L=L, A_eff=self.Aeff, T_K=T_K, **kwargs)

    def _brillouinThreshold(self, lambda_ref=1550e-9):
        L = getattr(self, 'Lt', getattr(self, 'L0', None))
        return brillouin_threshold(A_eff=self.Aeff, L=L, lambda_pump=lambda_ref)

    def _checkSBSThreshold(self, P_pump, lambda_ref=1550e-9, **kwargs):
        L = getattr(self, 'Lt', getattr(self, 'L0', None))
        return check_sbs_threshold(P_pump=P_pump, A_eff=self.Aeff, L=L,
                                    lambda_pump=lambda_ref, **kwargs)

    fiber_obj.calcSpBrilNoise    = types.MethodType(_calcSpBrilNoise,    fiber_obj)
    fiber_obj.brillouinThreshold = types.MethodType(_brillouinThreshold, fiber_obj)
    fiber_obj.checkSBSThreshold  = types.MethodType(_checkSBSThreshold,  fiber_obj)
    return fiber_obj


# ─────────────────────────────────────────────────────────────────────────────
# Validation self-tests
# ─────────────────────────────────────────────────────────────────────────────

def _run_self_tests(verbose=True):
    """
    Run nine sanity checks.  Returns True if all pass.

    Checks:
      1. nu_B at 1550 nm is in [10.5, 12.0] GHz
      2. g_B Lorentzian peaks at Omega_B
      3. g_B HWHM condition: g_B(Omega_B + Gamma_B/2) = g_B_peak/2
      4. Integral of Lorentzian = pi * g_B_peak * Gamma_B / 2  (analytical)
      5. Backward L_eff = L for lossless fiber (alpha -> 0)
      6. Backward L_eff < forward L_eff for lossy fiber
      7. n_th(Omega_B, 300K) in classical limit  (kT/hbar*Omega_B)
      8. SBS threshold at 25 km SMF-28: 2-6 mW range
      9. spBril far from Brillouin line ~ 0
    """
    PASS = 'PASS'
    FAIL = 'FAIL'
    all_pass = True

    def check(name, cond, got='', exp=''):
        nonlocal all_pass
        ok = bool(cond)
        if not ok:
            all_pass = False
        if verbose:
            tag = f'[{PASS}]' if ok else f'[{FAIL}]'
            print(f'  {tag}  {name}')
            if not ok:
                print(f'         got {got}, expected {exp}')

    if verbose:
        print('=' * 58)
        print('brillouin.py self-test suite')
        print('=' * 58)

    nu_B    = brillouin_freq_shift(1550e-9)
    Omega_B = 2 * _pi * nu_B

    check('nu_B(1550nm) in [10.5, 12.0] GHz',
          10.5e9 < nu_B < 12.0e9, f'{nu_B/1e9:.3f} GHz', '~11.1 GHz')

    gB_at_peak = float(g_B_lorentzian(Omega_B, Omega_B))
    check('g_B(Omega_B) = BRIL_G_PEAK',
          abs(gB_at_peak - BRIL_G_PEAK) / BRIL_G_PEAK < 1e-10,
          gB_at_peak, BRIL_G_PEAK)

    gB_hwhm = float(g_B_lorentzian(Omega_B + BRIL_GAMMA_RAD/2, Omega_B))
    check('g_B(Omega_B + Gamma/2) = g_B_peak / 2  (HWHM)',
          abs(gB_hwhm - BRIL_G_PEAK/2) / (BRIL_G_PEAK/2) < 1e-10,
          gB_hwhm, BRIL_G_PEAK/2)

    Om_int = np.linspace(1e6, 10*Omega_B, 1_000_000)
    integral = float(simpson(g_B_lorentzian(Om_int, Omega_B), x=Om_int))
    expected = BRIL_G_PEAK * _pi * BRIL_GAMMA_RAD / 2
    check('integral(g_B) = pi * g_B_peak * Gamma_B/2  (within 0.1%)',
          abs(integral - expected) / expected < 0.001,
          f'{integral:.4e}', f'{expected:.4e}')

    Leff_0 = float(effective_length_backward(25e3, 1e-30, 1e-30))
    check('L_eff_back(alpha=0) = L  (lossless fiber)',
          abs(Leff_0 - 25e3) / 25e3 < 0.01, Leff_0, 25e3)

    alpha = float(_fiber_loss_m(1550e-9))
    Leff_b = float(effective_length_backward(25e3, alpha))
    Leff_f = (1 - np.exp(-alpha*25e3)) / alpha
    check('L_eff_back < L_eff_fwd  (extra backward loss)',
          Leff_b < Leff_f,
          f'{Leff_b/1e3:.2f} km', f'< {Leff_f/1e3:.2f} km')

    nth    = float(thermal_phonon_number(Omega_B, 300.0))
    nth_cl = float(_kB * 300.0 / (_hbar * Omega_B))
    check('n_th(Omega_B, 300K) in [500, 620]',
          500 < nth < 620, f'{nth:.1f}', '~561')
    check('n_th ~ kT/hbar*Omega  (classical, within 0.3%)',
          abs(nth - nth_cl) / nth_cl < 0.003, f'{nth:.2f}', f'{nth_cl:.2f}')

    th = brillouin_threshold(85e-12, 25e3)
    check('SBS threshold (25km SMF-28) in [2.0, 6.0] mW',
          2.0 < th['P_threshold_mW'] < 6.0,
          f"{th['P_threshold_mW']:.2f} mW", '~3.6 mW')

    res = spBril_noise_in_channel(1310e-9, 1550e-9, 1e-9, 1e-3, 25e3, 85e-12, 300)
    check('SpBril (1310->1550nm, far from Brillouin) ~ 0',
          res['backward_photon_rate'] < 1e-3,
          f"{res['backward_photon_rate']:.2e}", '~0')

    if verbose:
        print('=' * 58)
        print('ALL TESTS PASSED' if all_pass else 'SOME TESTS FAILED')
        print('=' * 58)

    return all_pass


# ─────────────────────────────────────────────────────────────────────────────
# Demo / validation runner
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    import sys

    ok = _run_self_tests(verbose=True)
    if not ok:
        sys.exit(1)

    print()
    lam_p   = 1550e-9
    nu_B    = float(brillouin_freq_shift(lam_p))
    Omega_B = 2 * _pi * nu_B
    alpha   = float(_fiber_loss_m(lam_p))
    A_eff   = 85e-12

    dlam_B_pm = lam_p**2 * nu_B / _c * 1e12

    print('─' * 58)
    print('Numerical summary (SMF-28, 1550 nm, T=300 K)')
    print('─' * 58)
    print(f'  nu_B        = {nu_B/1e9:.3f} GHz')
    print(f'  delta_lam_B = {dlam_B_pm:.2f} pm')
    print(f'  Gamma_B     = {BRIL_DFREQ_HZ/1e6:.0f} MHz FWHM')
    print(f'  g_B_peak    = {BRIL_G_PEAK:.2e} m/W')
    print(f'  n_th(Omega_B, 300K) = {thermal_phonon_number(Omega_B, 300.):.1f}')
    print()
    print('SBS threshold vs fiber length:')
    print(f'  {"L (km)":>8}  {"L_eff_back (km)":>16}  {"P_th (mW)":>11}')
    for Lkm in [5, 10, 25, 50, 100]:
        th = brillouin_threshold(A_eff, Lkm*1e3, lambda_pump=lam_p)
        print(f'  {Lkm:>8}  {th["L_eff_back_m"]/1e3:>16.3f}  {th["P_threshold_mW"]:>11.2f}')

    print()
    print('Wavelength dependence of nu_B:')
    for lam_nm in [1310, 1380, 1450, 1550, 1620]:
        nu = float(brillouin_freq_shift(lam_nm*1e-9))
        print(f'  lambda={lam_nm} nm:  nu_B = {nu/1e9:.3f} GHz,  '
              f'delta_lam = {(lam_nm*1e-9)**2 * nu / _c * 1e12:.2f} pm')

    # ── Plots ────────────────────────────────────────────────────────────────
    print()
    print('Generating validation plots...')
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(2, 2, figsize=(13, 9))
    fig.suptitle('Brillouin Scattering: Validation and Characterisation\n'
                 'SMF-28 fibre, λ = 1550 nm, T = 300 K', fontsize=12)

    # ── Panel 1: Gain spectrum around Brillouin peak ──────────────────────
    ax = axes[0, 0]
    freq_off_MHz = np.linspace(-150, 150, 50_000)
    nu_p = _c / lam_p
    Om_q = 2*_pi * np.abs((nu_p + freq_off_MHz*1e6) - nu_p)
    # Shift x-axis to be relative to Brillouin peak
    Om_q_rel = 2*_pi * np.abs((nu_p + freq_off_MHz*1e6) - (nu_p - nu_B))
    gB_vals  = g_B_lorentzian(Om_q, Omega_B)
    ax.plot(freq_off_MHz - nu_B/1e6, gB_vals * 1e11, color='#1a6faf', lw=2)
    ax.axvline(0, color='gray', lw=0.7, ls=':')
    ax.axhline(BRIL_G_PEAK*1e11/2, color='#c0392b', lw=1.0, ls='--',
               label=f'HWHM = {BRIL_DFREQ_HZ/2e6:.0f} MHz')
    ax.set_xlabel('Frequency offset from Brillouin peak  (MHz)', fontsize=10)
    ax.set_ylabel('g$_B$  (×10$^{-11}$ m/W)', fontsize=10)
    ax.set_title('Lorentzian Brillouin gain spectrum', fontsize=10)
    ax.legend(fontsize=9)
    ax.grid(True, ls='--', lw=0.5, alpha=0.5)

    # ── Panel 2: SBS threshold vs fiber length ───────────────────────────
    ax = axes[0, 1]
    L_km_arr = np.logspace(np.log10(0.1), np.log10(316), 300)
    P_th_arr = np.array([
        brillouin_threshold(A_eff, Lk*1e3, lambda_pump=lam_p)['P_threshold_mW']
        for Lk in L_km_arr])
    ax.semilogx(L_km_arr, P_th_arr, color='#c0392b', lw=2, label='P_th (G=21)')
    ax.axhline(1.0,  color='#e67e22', lw=1, ls='--', label='1 mW')
    ax.axhline(10.0, color='#2ecc71', lw=1, ls='--', label='10 mW')
    ax.fill_between(L_km_arr, 0, P_th_arr, color='#c0392b', alpha=0.08)
    ax.axvline(25, color='gray', lw=0.8, ls=':')
    ax.text(26, 15, '25 km', fontsize=8.5, color='gray')
    ax.set_xlabel('Fibre length  L  (km)', fontsize=10)
    ax.set_ylabel('SBS threshold  P$_{th}$  (mW)', fontsize=10)
    ax.set_title('SBS threshold vs fibre length  (SMF-28, 1550 nm)', fontsize=10)
    ax.legend(fontsize=9)
    ax.grid(True, which='both', ls='--', lw=0.5, alpha=0.5)
    ax.set_ylim(0, 20)

    # ── Panel 3: SpBril noise vs pump power ─────────────────────────────
    ax = axes[1, 0]
    lam_Bs = _c / (_c / lam_p - nu_B)   # Stokes wavelength
    P_arr  = np.logspace(-3, 1, 200) * 1e-3
    N_arr  = np.array([
        spBril_noise_in_channel(lam_p, lam_Bs, 0.5e-9, P, 25e3, A_eff, 300.0
                                )['backward_photon_rate']
        for P in P_arr])
    P_th_25 = brillouin_threshold(A_eff, 25e3, lambda_pump=lam_p)['P_threshold_W']
    ax.loglog(P_arr*1e3, N_arr, color='#1a6faf', lw=2, label='SpBril (0.5 nm BW)')
    ax.axvline(P_th_25*1e3, color='#c0392b', lw=1.2, ls='--',
               label=f'P$_{{th}}$ = {P_th_25*1e3:.1f} mW')
    ax.set_xlabel('Pump power  P  (mW)', fontsize=10)
    ax.set_ylabel('Backward photon rate  (photons/s)', fontsize=10)
    ax.set_title(f'SpBril noise at Stokes wavelength\n'
                 f'λ$_{{\\mathrm{{Stokes}}}}$ = {lam_Bs*1e9:.4f} nm, L = 25 km', fontsize=9)
    ax.legend(fontsize=9)
    ax.grid(True, which='both', ls='--', lw=0.5, alpha=0.5)

    # ── Panel 4: Brillouin shift vs wavelength ───────────────────────────
    ax = axes[1, 1]
    lam_sw = np.linspace(1260e-9, 1680e-9, 500)
    nu_SiO2 = np.array([brillouin_freq_shift(l)         for l in lam_sw])
    nu_GeO2 = np.array([brillouin_freq_shift(l, m_GeO2=0.036) for l in lam_sw])
    ax.plot(lam_sw*1e9, nu_SiO2/1e9, color='#2c7bb6', lw=2, label='Pure SiO₂')
    ax.plot(lam_sw*1e9, nu_GeO2/1e9, color='#d7191c', lw=2, ls='--',
            label='3.6% GeO₂ (SMF-28 core)')
    for lam_mark, band in [(1310, 'O'), (1550, 'C')]:
        nu_m = float(brillouin_freq_shift(lam_mark*1e-9))
        ax.axvline(lam_mark, color='gray', lw=0.7, ls=':')
        ax.text(lam_mark+5, nu_m/1e9+0.15, f'{nu_m/1e9:.2f} GHz', fontsize=8, color='gray')
    ax.set_xlabel('Pump wavelength  (nm)', fontsize=10)
    ax.set_ylabel('Brillouin shift  ν$_B$  (GHz)', fontsize=10)
    ax.set_title('Brillouin frequency shift vs pump wavelength', fontsize=10)
    ax.legend(fontsize=9)
    ax.grid(True, ls='--', lw=0.5, alpha=0.5)

    plt.tight_layout()
    for ext in ('pdf', 'png'):
        fname = f'brillouin_validation.{ext}'
        plt.savefig(fname, dpi=160, bbox_inches='tight')
        print(f'  Saved: {fname}')
    plt.close()
